export const dataProduct = [
  {
    id:1,
     varian : 'Powder',
    title: 'Bedak MBK Powder Sachetan 13,6 gram White',
    price : 6000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/powder/powder-7.png',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
  productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'Pagi ini langit terlihat cerah meskipun sempat turun hujan semalam.',
   productLink : 'https://shopee.co.id/Bedak-MBK-Powder-Sachetan-13-6-gram-Dan-Box-200-gram-bedak-deodoran-legendaris-Varian-Putih-i.1736388240.56660827193?extraParams=%7B%22display_model_id%22%3A272631610843%2C%22model_selection_logic%22%3A2%7D',
  },
  {
    id:2,
    varian : 'Powder',
    title: 'Box 200 gram - bedak deodoran legendaris Varian White',
    price : 36000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/powder/powder-1.png',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'hhttps://shopee.co.id/Bedak-MBK-Powder-Sachetan-13-6-gram-Dan-Box-200-gram-bedak-deodoran-legendaris-Varian-Putih-i.1736388240.56660827193?extraParams=%7B%22display_model_id%22%3A272631610843%2C%22model_selection_logic%22%3A2%7D',
  },
  {
    id:3,
     varian : 'Powder',
    title: 'Bedak MBK Powder Sachetan 13,6 gram Varian Silver',
    price : 6000,
    image : 'assets/img/products/powder/powder-2.jpg',
    shippingTime : '< 2-3 hari',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'https://shopee.co.id/Bedak-MBK-Powder-Sachetan-13-6-gram-Dan-Box-200-gram-bedak-deodoran-legendaris-Varian-Silver-i.1736388240.56210822354?extraParams=%7B%22display_model_id%22%3A325945884290%2C%22model_selection_logic%22%3A2%7D',
  },
  {
    id:4,
    varian : 'Powder',
    title: 'Box 200 gram - bedak deodoran legendaris Varian Silver',
    price : 36000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/powder/powder-8.png',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'https://shopee.co.id/Bedak-MBK-Powder-Sachetan-13-6-gram-Dan-Box-200-gram-bedak-deodoran-legendaris-Varian-Silver-i.1736388240.56210822354?extraParams=%7B%22display_model_id%22%3A325945884290%2C%22model_selection_logic%22%3A2%7D',
  },

  {
    id:5,
    varian : 'Powder',
    title: 'Bedak Powder MBK Tin 60g - bedak deodoran legendaris Varian White',
    price : 20000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/powder/powder-6.webp',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'https://shopee.co.id/Bedak-Powder-MBK-Tin-60g-bedak-deodoran-legendaris-Allvarian-i.1736388240.56510721011?extraParams=%7B%22display_model_id%22%3A380937840735%2C%22model_selection_logic%22%3A2%7D',
  },
    {
      id:6,
    varian : 'Powder',
    title: 'Bedak Powder MBK Tin 60g - bedak deodoran legendaris Varian Silver',
    price : 20000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/powder/powder-9.png',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'https://shopee.co.id/Bedak-Powder-MBK-Tin-60g-bedak-deodoran-legendaris-Allvarian-i.1736388240.56510721011?extraParams=%7B%22display_model_id%22%3A380937840735%2C%22model_selection_logic%22%3A2%7D',
  },

  // Roll
    {
      id:7,
    varian : 'Roll',
    title: 'MBK Deodorant Roll On Pria dan Wanita 40ml Variant Purple',
    price : 15000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/roll/roll-1.png',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'https://shopee.co.id/MBK-Deodorant-Roll-On-Pria-dan-Wanita-40ml-Variant-Ungu-i.1736388240.47510781088?extraParams=%7B%22display_model_id%22%3A340940911178%2C%22model_selection_logic%22%3A2%7D',
  },
    {
      id:8,
    varian : 'Roll',
    title: 'MBK Deodorant Roll On Pria dan Wanita 40ml Variant Grey',
    price : 15000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/roll/roll-2.png',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'https://shopee.co.id/MBK-Deodorant-Roll-On-Pria-dan-Wanita-40ml-Variant-Black-i.1736388240.53110765426?extraParams=%7B%22display_model_id%22%3A425940846075%2C%22model_selection_logic%22%3A2%7D',
  },
    {
      id:9,
    varian : 'Roll',
    title: 'MBK Deodorant Roll On Pria dan Wanita 40ml Variant Blue',
    price : 15000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/roll/roll-3.png',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'https://shopee.co.id/MBK-Deodorant-Roll-On-Pria-dan-Wanita-40ml-Variant-Biru-i.1736388240.54160765505?extraParams=%7B%22display_model_id%22%3A405940874229%2C%22model_selection_logic%22%3A2%7D',
  },
    {
      id:10,
    varian : 'Roll',
    title: 'MBK Deodorant Roll On Pria dan Wanita 40ml Variant Pink',
    price : 15000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/roll/roll-5.png',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'https://shopee.co.id/MBK-Deodorant-Roll-On-Pria-dan-Wanita-40ml-Variant-Pink-i.1736388240.51860754677?extraParams=%7B%22display_model_id%22%3A350940947236%2C%22model_selection_logic%22%3A2%7D',
  },
]; 
