export const dataProduct = [
  {
    id:1,
     varian : 'Powder',
    title: 'Bedak MBK Powder Sachetan 13,6 gram White',
    price : 6000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/powder/powder-7.png',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
  productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'Pagi ini langit terlihat cerah meskipun sempat turun hujan semalam.',
   productLink : 'https://id.shp.ee/7q3drsbu',
  },
  {
    id:2,
    varian : 'Powder',
    title: 'Box 200 gram - bedak deodoran legendaris Varian White',
    price : 36000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/powder/powder-1.png',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'https://id.shp.ee/7q3drsbu',
  },
  {
    id:3,
     varian : 'Powder',
    title: 'Bedak MBK Powder Sachetan 13,6 gram Varian Silver',
    price : 6000,
    image : 'assets/img/products/powder/powder-2.jpg',
    shippingTime : '< 2-3 hari',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'https://id.shp.ee/7q3drsbu',
  },
  {
    id:4,
    varian : 'Powder',
    title: 'Box 200 gram - bedak deodoran legendaris Varian Silver',
    price : 36000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/powder/powder-8.png',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'https://id.shp.ee/7q3drsbu',
  },

  {
    id:5,
    varian : 'Powder',
    title: 'Bedak Powder MBK Tin 60g - bedak deodoran legendaris Varian White',
    price : 20000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/powder/powder-6.webp',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'https://id.shp.ee/7q3drsbu',
  },
    {
      id:6,
    varian : 'Powder',
    title: 'Bedak Powder MBK Tin 60g - bedak deodoran legendaris Varian Silver',
    price : 20000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/powder/powder-9.png',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'https://id.shp.ee/7q3drsbu',
  },

  // Roll
    {
      id:7,
    varian : 'Roll',
    title: 'MBK Deodorant Roll On Pria dan Wanita 40ml Variant Purple',
    price : 15000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/roll/roll-1.png',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'https://id.shp.ee/7q3drsbu',
  },
    {
      id:8,
    varian : 'Roll',
    title: 'MBK Deodorant Roll On Pria dan Wanita 40ml Variant Grey',
    price : 15000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/roll/roll-2.png',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'https://id.shp.ee/7q3drsbu',
  },
    {
      id:9,
    varian : 'Roll',
    title: 'MBK Deodorant Roll On Pria dan Wanita 40ml Variant Blue',
    price : 15000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/roll/roll-3.png',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'https://id.shp.ee/7q3drsbu',
  },
    {
      id:10,
    varian : 'Roll',
    title: 'MBK Deodorant Roll On Pria dan Wanita 40ml Variant Pink',
    price : 15000,
    shippingTime : '< 2-3 hari',
    image : 'assets/img/products/roll/roll-5.png',
   city : 'Kab. Tangerang' ,
   countGoodsSold :'10+ terjual',
    productDescriptionGeneral : 'lorem ipsum ktar yaout litu hejkaha',
   productDescriptionhowToUse : 'lorem ipsum ktar yaout litu hejkaha',
   productLink : 'https://id.shp.ee/7q3drsbu',
  },
]; 
